redsunservers/SuperZombieFortress

- addons/sourcemod/scripting/superzombiefortress.sp
`delete` should already check if the handle is null, so any other checks before `delete` are pointless.
> Get rid of CloseHandle_2 and unnecessary INVALID_HANDLE checks

- addons/sourcemod/scripting/szf/pickupweapons.sp
- addons/sourcemod/scripting/szf/weapons.sp
Returning false in a `eWeapon_OnPickup` function will now actually prevent player from picking up a weapon/pickup (Previously it was weird and would only work on pickups).
Also made medkit unpickable if player has full health.
> Changes to eWeapon_OnPickup

- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/sound.sp
(this was just for VO, but it escalated as it went on)
This PR looks into a few issues:
- There was a lot of infected VO that was unintentionally unused, yet precached, all of them will be made use of.
- The gamemode would give a lot of "blank sound not precached" warnings to the server console, most of them will be stopped (only exception is the first music bit a client hears after the gamemode has been loaded)
- Bacteria (special infected global callout) didn't play correctly, it will be fixed for classes that unintentionally didn't make use of it.
Changes:
**VO:**
Regular infected:
- all stock-voiceline-specific sounds work properly. Before, the only different (as in, not idle) infected voiceline that would play was to call for Medic while taunting, most of it was because the code was …
> Fixes for several sounds

- README.md
- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/stocks.sp
New method to create/equip Voodoo models is similar to how my VSH-Rewrite is done, using `TF2_CreateAndEquipWeapon` stock to create wearable and entprop `m_nModelIndexOverrides` to get model correctly. Even though it not really a weapon, it still somehow works for wearable aswell.
Also changed index of wearable from 5023 (paint can) to correct index for each 9 voodoo cosmetics. This doesn't really make much difference, but inspecting cosmetics while dead/spectator now shows voodoo instead of paint can.
> Update Voodoo models to not require tf2items

- addons/sourcemod/scripting/superzombiefortress.sp
Both special infected scout currently uses stock Bat, which is boring. Lets give spooky melees instead, Hunter with Unarmed Combat and Kingpin with Bat Outta Hell.
Note that this also would made hunter a indirect nerf, because of Unarmed Combat using fish's mechanic **"ARM KILL!"**. This helps survivors (and zombies) know hunter attacking a survivor, likely stunned and beating to death.
Thanks to Robotnik for bringing up this idea.
> Give Hunter Unarmed Combat, Kingpin Bat Outta Hell

- addons/sourcemod/scripting/superzombiefortress.sp
See issue #22 
Prevents anyone able to pickup Sandvich the first 3 seconds it get thrown, and owner can't recollect his own sandvich.
Second Banana damage also nerfed from 40 to 30, but can still be instant picked up for everyone, like the old sandvich.
> Nerf Sandvich to act more like a "trap"

- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/stocks.sp
Most of the changes is just small code cleanups, but the main fix is here:
https://github.com/redsunservers/SuperZombieFortress/blob/63f4593a7090741dc4572ea3758c2a82f7fcb20b/addons/sourcemod/scripting/szf/stocks.sp#L797
Just not validated to other users, only visible to client itself
> Fix zombie models not visible to users

- addons/sourcemod/configs/szf/weapons.cfg
The attribute was there, but its value was wrong (was at 10%).
Fix for issue #30.
> Fix Back Scratcher not having the 90% healing received from healers penalty

- addons/sourcemod/scripting/superzombiefortress.sp
Currently in 1st round, if 4 or less survivors and more than 16 connecting players, all survivors get 300 starting health.
Since there a +60 seconds setup, it quite rare to see this happens only for starting health. Along with that, "new" zombie damage scale is already fairly low during early-game with low survivors and high zombies. There isn't really any point keeping it.
> Remove survivors 1st round buff

- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/stocks.sp
Every time `DealDamage` get called, it spawns an entity while also dispatching quite a few values to deal damage, not a nice method to do when `SDKHooks_TakeDamage` works much simpler and faster.
> Kill DealDamage, use SDKHooks_TakeDamage instead

- addons/sourcemod/scripting/superzombiefortress.sp
This isn't supposed to be a balance change, but rather a change that gives players better visual feedback. Even if it rarely happens, some players get confused when they get one-shot as a Smoker, so having a Kunai (which conveniently also changes max hp to 70) will help them understand that they're very squishy right away.
The lifesteal attribute still being there shouldn't be a problem since all backstab kills will happen when the target is at very low hp anyway.
> Smoker: instead of directly changing his hp to 70, give him a Kunai

- addons/sourcemod/scripting/superzombiefortress.sp
Error has been thrown from `SDKHooks_TakeDamage` on invalid attacker, since there was no check for it.
> Add valid attacker check for goo damage

- addons/sourcemod/scripting/szf/weapons.sp
SourcePawn 1.10 had an update, warns about legacy enum struct removed in 1.11.
While `eWeaponsRarity` may doesn't look like legacy enum struct, it actually an array of int, which what makes it an enum struct.
> Fix legacy enum struct compile warning

- addons/sourcemod/scripting/superzombiefortress.sp
This change lets survivors be able to normally move out of spawn without being overwhelmed when either it's the first round or players intentionally switch teams after a round begins, especially in maps that move spawn points after setup ends. No changes were made during the waiting for players, active round and post round periods.
New behaviour:
- Players are still allowed to go into the spectator team as much as they please.
- If a player tries to join the infected team as a survivor during grace period, the gamemode will simply not let them and do nothing besides tell them they aren't allowed to do so in chat.
- They'll be allowed to switch teams again when it ends, though.
- If a player tries to join any team as a spectator, or when first selecting a team during grace period, they'll …
> Disallow players from joining the infected team during grace period/setup

- addons/sourcemod/scripting/superzombiefortress.sp
The plugin restyling (#47) changed a lot of things, but an issue it brought is that with a change to the Round State enum struct, it skips over a step and sees the waiting for players period as an actual round, and this breaks a couple of things:
- The first round skip immunity/mechanic is ignored and will catch players after a set amount of time during waiting for players and will force undeserving players to the infected team in the first round.
- As a result, the anti-exploiting feature introduced with PR #44 will also be active during waiting for players, making everyone (except the very first player) unable to join either team until the emergency 45 sec grace period timer ends, confusing a lot of people.
This PR simply re-adds the waiting for players step as a round state.
> Fix grace period happening during Waiting for Players

- addons/sourcemod/scripting/superzombiefortress.sp
This really only affects where player is last man with less than 6 living players, attempting to pick up strength powerup does nothing since lastman-minicrit forcefully removed it.
New code simply just give minicrit at very short amount of time on every frame. Not removing minicrit from unexpected places, if less than 6 living players.
> Re-do last man minicrit code

- addons/sourcemod/gamedata/szf.txt
- addons/sourcemod/scripting/superzombiefortress.sp
`SDKHook_StartTouch` and `SDKHook_Touch` on Sandman ball can rarely not call on touching player, and stuns instead of doing usual goo. Use actual sandman's touch functions instead, `CTFStunBall::ShouldBallTouch`.
There also `CTFStunBall::ApplyBallImpactEffectOnVictim` that could be hooked instead, but that does not call when ball is rolling on the round and touching player, unlike `SDKHook_StartTouch` and `SDKHook_Touch`.
> Update detection into goo touching player

- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/stocks.sp
Apparently back in slag payload and attack/defense was supported/played in SZF? Whatever it is, we never really support this for +3 years in redsun, probably have bugs and errors thrown.
`sm_szf_force_on` is however still here, allowing to force enable SZF in `zf_`/`szf_` prefix maps for whatever weird maps out there, i dunno.
> Remove non-szf maps support

- addons/sourcemod/scripting/superzombiefortress.sp
- scripts/install.sh
Apparently hooking `GiveNamedItem` while TF2Items' hook is active causes crashes so we do a new thing now:
* If TF2Items is loaded we use the `TF2Items_OnGiveNamedItem` forward
* Otherwise we hook `GiveNamedItem` ourselves through dhooks
> No more crashes on GiveNamedItem

- addons/sourcemod/scripting/superzombiefortress.sp
Could fix an issue where players occasionally don't get stripped of their weapons correctly
> Block GiveNamedItem instead of ignoring it if one of the passed pointers is null

- addons/sourcemod/scripting/superzombiefortress.sp
Player selection for Tank spawns has always worked as intended - it chooses the player who has dealt the most damage for that round - but the way it sees how much damage a player has dealt can be questionable at times.
How it works now: Everyone (obviously) starts at 0 damage and all damage dealt is added towards a damage counter, even damage done as a survivor. Players who joined the server mid-round have their damage counter set to the average damage dealt by all players, **including survivors**. When a Tank dies, that player's damage counter is also set to the average damage dealt by all players.
This means that players who died or (especially) joined the server mid-round have a much greater chance to become a Tank, as damage done by survivors greatly exceed damage done by infected. …
> (Slight) rework for damage detection for Tank selection

- addons/sourcemod/gamedata/szf.txt
- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/stocks.sp
Fix #53 
`CTeamplayRoundBasedRules::RoundRespawn` function is used for respawning everyone,  called right before `teamplay_round_start` event, but also switch and scramble teams. This PR hooks `CTeamplayRoundBasedRules::RoundRespawn` so round start stuffs can be done before client respawns, so client class and team can be prepared for `CTeamplayRoundBasedRules::RoundRespawn` respawning everyone, rather than force respawn everyone, costing more ents during round start.
However we need to be careful with switch and scramble teams inside `CTeamplayRoundBasedRules::RoundRespawn` as that can cause players to spawn in wrong team. team switch is prevented by `CTeamplayRoundBasedRules::SetWinningTeam` param `bSwitchTeams`, and scramble teams by convar `mp_scrambleteams_auto`.
This whole change …
> Prevent unneeded respawns during round start

- addons/sourcemod/scripting/superzombiefortress.sp
When grace period ends and red tried to change loadout or its class, they would get force respawned and moved to zombie team. Disable func_respawnroom to prevent client accidentally respawn.
Reported at https://github.com/DFS-Servers/BugReportsAndSuggestions/issues/246
> Disable red's func_respawnroom after grace period ends

- addons/sourcemod/configs/szf/weapons.cfg
there's a 25% additional explosion damage att on this weapon, however since zombies don't have that and 25% is a lot of damage for scunt i converted it down to 10% additional general damage
i also nulled out explosion damage because additional explosion damage on turtle attack/pen15/etc. lol
> make the candy cane hurt more but not a lot

- addons/sourcemod/scripting/szf/event.sp
- addons/sourcemod/scripting/szf/pickupweapons.sp
- addons/sourcemod/scripting/szf/sdkhook.sp
- addons/sourcemod/scripting/szf/sound.sp
- Uses ``SpeakResponseConcept`` with existing MvM response concepts instead of grabbing a random sound from a hardcoded array
- Adds voice lines for when a tank spawns
- Utilizes different weapon pickup lines for different weapon rarities
Didn't test this, but it should work and fit quite nicely
> Replace hardcoded tank and weapon pickup voice lines

- addons/sourcemod/gamedata/szf.txt
- addons/sourcemod/scripting/szf/dhook.sp
- Commit redsunservers/SuperZombieFortress@6bf3a616d0b9276cf5b217d6ee4c3c9cc276b06f has broken the crash fix I had submitted https://github.com/redsunservers/SuperZombieFortress/pull/65
Moreover the move to dhook over a config file was unproperly done the argument was set as `entity` instead of `int` like it should have been, as mentioned in the PR above. I.e to pass a raw pointer.
This misport has probably prompted the commit mentioned as well.
Finally commit redsunservers/SuperZombieFortress@3073035178496d82f899d712f5d85b7db67ba348 introduced another mishap.
Considering `game_ui` as a player/client. This error has also been corrected, fetching properly the client from the entity's datamap. (Not sure what this plugin function is even attempting)
Note: those changes haven't been tested, …
> Broken crash fix

- addons/sourcemod/configs/szf/weapons.cfg
- addons/sourcemod/translations/superzombiefortress.phrases.txt
Atomizer: Was too annoying and used to stall rounds
Removed Triple jump and its airborne attribute (there were no separate attributes)
Added "apply z velocity on damage" attribute
Eureka Effect: Despite many tests, in no situation the buildings' health boost has ever been useful and the metal penalty just makes this melee a liability
Remove buildings' health boost.
Added periodic metal regen (5 every 5 seconds)
> Atomizer and Eureka Effect reworks

- addons/sourcemod/configs/szf/weapons.cfg
As it is, Winger feels too good to get, especially at the start of a round as the bonus jump height makes the Scout too slippery for zombies to hit as well as providing unparalleled vertical mobility early that can be abused to accomplish feats such as reaching the first cap at Graveyard without needing to glide on other props or kiting a horde of zombies by jumping between two elevated spots in a cap zone such as the penultimate cap on Cityhunter while still being a competent enough weapon with the slight damage bonus. Making it an uncommon drop should be a fair enough change to the weapon without touching the weapon itself.
> Make Winger an uncommon weapon.

- addons/sourcemod/configs/szf/weapons.cfg
- addons/sourcemod/translations/superzombiefortress.phrases.txt
After many games, it's been obvious the melee of choice for demoman has been the Eyelander as it grants uncomprable buffs upon reaching 5 heads, which nullified the need of the player to find a sticky launcher/grenade launcher. This nerf aims at reducing the buff and increase the risks during the head collection process. Plus prevents the demoknight to go lightspeed to avoid the slow and strong zombies as last survivor to regain health from weak zombies.
Eyelander: -15% Speed penalty and -35 Max Health
In order to encourage other melee weapons, I have also included a small buff to Skullcutter. Extra damage and the move speed penalty only applies when the player holds the weapon. Making it a strong early game choice until the player finds a weapon to get rid of the speed penalty. …
> Nerf Eyelander, buff Skullcutter

- addons/sourcemod/scripting/include/superzombiefortress.inc
- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/convar.sp
- addons/sourcemod/scripting/szf/event.sp
- addons/sourcemod/scripting/szf/forward.sp
- addons/sourcemod/scripting/szf/pickupweapons.sp
- addons/sourcemod/scripting/szf/sdkhook.sp
- Fixed disguise models staying between rounds and if the plugin is unloaded
- Player no longer respawns if he/she just died as a survivor and respawned before the "You have perished" message
- Fixed viewmodels staying between rounds
- Fixed having 1% chance of random frenzy and tank instead of frenzy even when ConVar set to 0
- Improved code to only use `GetGameTime` once in a function
- Added sm_szf_tank_stab for server owners to control how much backstab damage deals
- Added sm_szf_stun_immunity for server owners to set stun immunity for X seconds after being stunned
- Added kill icon support for destroyed buildings
- Added SZF_ShouldPickupWeapon forward for getting info before picking up a weapon
- Added a slowdown for Spitter's gas
> Additions & Fixes

- addons/sourcemod/scripting/superzombiefortress.sp
Fixes frenzies from occurring when a logic_relay without a name is triggered.
> Fix Relay Frenzy

- addons/sourcemod/configs/szf/weapons.cfg
- addons/sourcemod/scripting/include/superzombiefortress.inc
- addons/sourcemod/scripting/szf/config.sp
- addons/sourcemod/scripting/szf/stocks.sp
Allows szf_weapon_static to place weapons such as the Rocket Jumper and Sticky Jumper. 
Adds the "static" rarity in the weapons config, only szf_weapon_static can spawn those weapons.
> Add support for unconventional static weapons

- addons/sourcemod/scripting/szf/event.sp
Event_PlayerBuiltObject had an issue where it would no longer disable the ammo after redeploy.
This was being abused, so we looked into it.
The reason this was an issue, was because the health had to not be set again, so this needed an inner if, instead of an all-encompassing if.
> Fix Dispenser giving ammo again after re-deploy

- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/stocks.sp
Hardy Laurel was restricted because rome vision was used for spy disguising as special infected with custom model, but we can allow equip Hardy Laurel, just without rome vision attribute.
> Allow equip Hardy Laurel

- addons/sourcemod/configs/szf/classes.cfg
- addons/sourcemod/scripting/szf/infected.sp
Adds OnDeath callback for Jockey infected which resets target.
OnThink callback is never called after infected dies. This means that Jockey's target is never reset when the jockey is killed and his target survives. And when the same player becomes Jockey again, it will immediately teleport to its previous target if it's alive and not infected.
> Reset Jockey target

- addons/sourcemod/scripting/szf/dhook.sp
87a2dc8bb61ea1b66e94d483d09679d6cc0b4141 allowed all melee hits to ignore teammates, but this broke the Soldier's whip speed boost.
This PR reverts the Disciplinary Action to the previous behavior.
> Fix the Disciplinary Action not hitting teammates

- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/convar.sp
- addons/sourcemod/scripting/szf/infected.sp
If survivor is facing direction that jockey is not looking at, both players will stand still. This change will give full control of the player and Jockey will become a bit more similar to L4D with the ability to take the survivor away from the rest or to a deadly environment, bringing more tactics for this special infected.
> Buff Jockey move target speed

- addons/sourcemod/scripting/superzombiefortress.sp
Fixes a specific case of players being accidentally flagged as skipping playing as infected when taking someone else's spot in the server (who actually likely skipped), then joining spectator.
This probably won't solve all accidental flagging, but may as well do it for this case.
Also moves resetting `g_bWaitingForTeamSwitch` from `OnClientDisconnect` to `OnClientPutInServer` so everything is in the same place.
> Reset players' 'started as zombie' timestamp when joining

- addons/sourcemod/scripting/szf/infected.sp
The Charger can sometimes crit after charging, this is because of SZF not accounting for the Demoman's charge meter, that is active even if you don't have a shield. It will always empty out before the charge is finished, if it empties out right before the Charger is allowed to swing their melee, it will crit. It may run out of charge sooner for whatever reason and that makes the melee swing not crit.
The critting was deemed to be a bug, so we're removing it by keeping the charge meter that is invisible to players at 100% during the charge.
> Charger: remove inconsistent end-of-charge crit

- addons/sourcemod/scripting/szf/dhook.sp
This PR removes the speed bonus non-special infected and Tank get while set ablaze. Mechanics where you punish your whole team for just playing the game are no fun.
> Remove infected/Tank speed boost while on fire

- addons/sourcemod/gamedata/szf.txt
- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/classes.sp
- addons/sourcemod/scripting/szf/dhook.sp
- addons/sourcemod/scripting/szf/event.sp
- addons/sourcemod/scripting/szf/sdkcall.sp
- addons/sourcemod/scripting/szf/sdkhook.sp
- addons/sourcemod/scripting/szf/stocks.sp
Previously it only allows to disguise with matching target's class due to default disguise look not having zombie effects, giving an obvious look.
This change makes it so that if disguising as a class that no zombies is playing as, it then changes the look to have zombie skin, zombie cosmetic, and SZF's default melee weapon. This should make it as identical as any other zombies.
Disguising as Spy is disallowed because clientside does not allow to be able to show zombie skin, instead showing as a normal spy with a random mask class.
Disguising as Engineer however does not show it's Gunslinger hand correctly, which I'm not sure if it's possible to fix.
> Allow disguise as anyone except Spy

- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/console.sp
- addons/sourcemod/scripting/szf/dhook.sp
Currently players are only guaranteed to be survivor if starting zombie in previous round. This update makes it more rotational, force starting zombies to anyone who has not been so for the longest. This would make it that players are expecting to be only zombie once for ~4 rounds, instead of a possibility to be zombie twice or never.
> Improve starting zombie cooldown

- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/event.sp
- Possible fix on client disconnecting or survivor death not applying correctly
- Possible fix on skip detection by force mapchange
- Loosen requirements on skip to force set zombie next time.
> Few updates to zombie skip detection

- addons/sourcemod/scripting/szf/sdkhook.sp
Halves damage on each additional sandvich that has been picked up in the past second, making huge stacks of them not insta-kill anymore.
Not tested.
> Reduce damage of stacked Zombie Sandviches

- addons/sourcemod/configs/szf/classes.cfg
- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/convar.sp
- addons/sourcemod/scripting/szf/infected.sp
- addons/sourcemod/translations/superzombiefortress.phrases.txt
- Adds `sm_szf_tank_debris_lifetime`, which makes debris thrown by Tanks despawn after the specified amount of time. Default is 20.0 and can be set to 0.0 to never despawn. This is to prevent servers from lagging because of too many physics objects being active at once.
- Adds a spawn message for the Tank, similar to other special Infected. Since the Tank now has a "special ability," it makes sense to let players know about it.
> Add a bit of QoL related to the Tank

- addons/sourcemod/configs/szf/classes.cfg
Increases rage cooldown by three seconds (aka substantially increasing cooldown on missing a pounce). Probably one of the best special infected currently in the mode for being able to lock down and potentially kill a survivor by themselves. Only having a three second cooldown on missing a pounce is too generous, especially compared to Jockey which has a longer cooldown on miss with a similar, but more situational power.
> Hunter: Longer Pounce Cooldown

- addons/sourcemod/scripting/superzombiefortress.sp
- addons/sourcemod/scripting/szf/convar.sp
Currently the scale was quite complicated to calculate, but a sudden change from scaling likely comes from the ^3.0 exponential, and last control point can double up the scaling.
The new formula now have it all scaled by linear. Map progress increases scale up to 40%, and few survivors can lower scale down by 90%. Last control point now only increases scale up by a flat +0.1.
Want to see this get tested before merging it.
> Update formula for zombie damage scale

- addons/sourcemod/configs/szf/weapons.cfg
- addons/sourcemod/translations/superzombiefortress.phrases.txt
Replaces the health drain mechanic on "The Gloves of Running Urgently" and "The Eviction Notice" with Marked-For-Death while the weapon is active.
Reason: Health drain is just not a fun mechanic.
> Replace health drain with Marked-For-Death while the weapon is active on Heavy's melee weapons
