addons/sourcemod/configs/szf/weapons.cfg, addons/sourcemod/scripting/superzombiefortress.sp, addons/sourcemod/scripting/szf/config.sp, addons/sourcemod/scripting/szf/pickupweapons.sp, addons/sourcemod/scripting/szf/stocks.sp, addons/sourcemod/scripting/szf/weapons.sp
Ok so basically every non-melee weapon and pickup can now be added, removed or changed through the `weapons.cfg` file.
Everything should feel the same gameplay-wise unless i fucked something up
=> Smol rework of non-melee weapons + configs

addons/sourcemod/scripting/superzombiefortress.sp
Smoker can actually see his tongue now
Before
After
=> Slight improvement to Smoker's beam

addons/sourcemod/scripting/superzombiefortress.sp
This doesn't seem to break fast respawns btw
=> Prevent g_hFastRespawnArray from growing to unreasonable sizes

addons/sourcemod/scripting/superzombiefortress.sp
Naughty kids like to be naughty by spam refilling goo in spawnroom to throw.
This change force sets goo cooldown to same as previous when respawned, if ball not refilled. This means refilling goo by spam respawning takes same amount of time as simply waiting for cooldown to end.
=> Prevent goo spam from refilling in spawn

addons/sourcemod/scripting/superzombiefortress.sp
Never meant to be enabled in the first place, surprised this did not happen until now
=> Kill all dropped weapon

addons/sourcemod/gamedata/szf.txt, addons/sourcemod/scripting/superzombiefortress.sp, addons/sourcemod/scripting/szf/stocks.sp
Less `TF2_RemoveWeaponSlot` = less lag :)
=> Use a CTFPlayer::GiveNamedItem hook to remove player's primary/secondary weapons 

addons/sourcemod/scripting/superzombiefortress.sp
Seems to crash quite frequent by reloading plugins and/or clients rejoining, `GiveNamedItem` not unhooked correctly.
@haxtonsale
=> Fix crash from GiveNamedItem

README.md, addons/sourcemod/scripting/include/superzombiefortress.inc, addons/sourcemod/scripting/superzombiefortress.sp, scripts/install.sh
tldr https://github.com/redsunservers/VSH-Rewrite/pull/122
Hopefully the last change need to do with those bullshit ~~probably not~~
Though we really need to split up superzombiefortress.sp to more files, eventually
=> Improve handling GiveNamedItem with TF2Items

addons/sourcemod/scripting/superzombiefortress.sp
https://github.com/redsunservers/SuperZombieFortress/issues/61
=> Check for the backstab

addons/sourcemod/scripting/superzombiefortress.sp
If special infected spawned but as incorrect class, "you are now X" get printed twice and tank was spawned with buffed health, but respawned back to 300.
Figure out which class client should play first, force respawn if needed then give special infected stuffs.
=> Fix tank and special infected spawns

addons/sourcemod/configs/szf/weapons.cfg
=> Have the K.G.B grant minicrits instead of crits on kill for 3 seconds

addons/sourcemod/configs/szf/weapons.cfg, addons/sourcemod/scripting/szf/event.sp, addons/sourcemod/translations/superzombiefortress.phrases.txt
Eureka grants 33% extra max health to the buildings
Vitasaw increases the Uber building rate by 15%
=> Eureka and Vitasaw buffs

addons/sourcemod/configs/szf/classes.cfg, addons/sourcemod/scripting/superzombiefortress.sp, addons/sourcemod/scripting/szf/config.sp, addons/sourcemod/scripting/szf/event.sp, addons/sourcemod/scripting/szf/infected.sp
Ability to set the Morale gained upon killing a specific zombie in the class config
=> Configurable Morale

addons/sourcemod/translations/jp/superzombiefortress.phrases.txt
this is probably (definitely) *super* scuffed, done mostly with google translate and periodic tf2 wiki jp page checking
i'm sure someone could do it better with actual translation but this was a neat way to pass time
=> add weeb (jp) translation

addons/sourcemod/gamedata/szf.txt, addons/sourcemod/scripting/superzombiefortress.sp, addons/sourcemod/scripting/szf/dhook.sp
* Replaced all DHook function calls with their methodmap equivalents
* Replaced all generic ``Handle`` types with new methodmap types
* Removed unnecessary parameters in callbacks
* Removed a fix for ``this`` pointer in post hooks being ``null`` as this was fixed in https://github.com/peace-maker/DHooks2/pull/8
Haven't tested it, but it should work fine.
=> Use DHooks methodmap API

addons/sourcemod/scripting/szf/pickupweapons.sp
For consistancy as we got common and rare non-expiring weapons, this adds `szf_weapon_uncommon_spawn` for use by map makers.
The PR also makes them so spawned weapons of any quality is only picked once
=> Add szf_weapon_uncommon_spawn for map makers

.github/workflows/compile.yml, .github/workflows/package.yml, README.md, scripts/version.sh
=> More GitHub actions fix

addons/sourcemod/scripting/szf/pickupweapons.sp
The value returned is always 0, this workaround is needed.
=> Fix weapon filtering

README.md
closes #161 
Contains relevant information about the game mode ( Objectives, gameplay)
=> Updates readme to contain further information about the gamemode

addons/sourcemod/configs/szf/classes.cfg
We do not talk about what happened at Sugarmill Escape in Raiden on 6th September 2024.
=> Prevent Amputator able to heal Tank
